viewer:
  name: "BioNGFF Viewer"
  version: "0.1.0"
  repo: "https://github.com/BioNGFF/biongff-viewer"
  template_url: "https://biongff.github.io/biongff-viewer/?source={DATA_URL}"

capabilities:
  # Enumeration of OME-Zarr versions that can be loaded
  ome_zarr_versions: [0.4, 0.5]

  # Are axis names and units respected?
  axes: true

  # Are scaling factors respected on multiscales?
  scale: false

  # Are translation factors respected on multiscales (including subpixel offsets for lower scale levels)?
  translation: false

  # Does the tool support multiple channels?
  channels: true

  # Does the tool support multiple timepoints?
  timepoints: true

  # Are labels loaded when available?
  labels: true

  # Are HCS plates loaded when available?
  hcs_plates: true

  # Does the viewer handle multiple images in a bioformats2raw layout?
  bioformats2raw_layout: true

  # Is the OMERO metadata used to e.g. color the channels?
  omero_metadata: true
